### ISSUE TITLE
hide login id and password of mysql to .env file.

### ISSUE THREAD

**Issue by Ashish1323** [victorsaad00/crud-nodejs#1]
![u](https://user-images.githubusercontent.com/42762022/93815410-8b7ec100-fc73-11ea-87ba-aa60757ebccb.JPG)

https://www.npmjs.com/package/dotenv

**Comment by victorsaad00** [comment]
Thank you a lot sir, i’m still learning this things !

**Comment by Ashish1323** [comment]
Keep It Up Brother!!
